export const ALARMS_LIST_REQUEST = "ALARMS_LIST_REQUEST";
export const ALARMS_LIST_SUCCESS = "ALARMS_LIST_SUCCESS";
export const ALARMS_LIST_FAIL = "ALARMS_LIST_FAIL";

export const ALARMS_CREATE_REQUEST = "ALARMS_CREATE_REQUEST";
export const ALARMS_CREATE_SUCCESS = "ALARMS_CREATE_SUCCESS";
export const ALARMS_CREATE_FAIL = "ALARMS_CREATE_FAIL";

export const ALARMS_UPDATE_REQUEST = "ALARMS_UPDATE_REQUEST";
export const ALARMS_UPDATE_SUCCESS = "ALARMS_UPDATE_SUCCESS";
export const ALARMS_UPDATE_FAIL = "ALARMS_UPDATE_FAIL";

export const ALARMS_DELETE_REQUEST = "ALARMS_DELETE_REQUEST";
export const ALARMS_DELETE_SUCCESS = "ALARMS_DELETE_SUCCESS";
export const ALARMS_DELETE_FAIL = "ALARMS_DELETE_FAIL";
